Predicting if a person would buy life insurnace based on his age using logistic regression

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import keras

%matplotlib inline

In [2]:
df = pd.read_csv("Insurance_Data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X = df[['age','affordibility']]
y = df.bought_insurance
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

### scaling

In [5]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age']/100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age']/100

In [6]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train_scaled,y_train,epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7534 - accuracy: 0.5000
Epoch 2/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7529 - accuracy: 0.5000
Epoch 3/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7525 - accuracy: 0.5000
Epoch 4/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7521 - accuracy: 0.5000
Epoch 5/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7517 - accuracy: 0.5000
Epoch 6/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7512 - accuracy: 0.5000
Epoch 7/500
1/1 [==============================] - 0s 1ms/step - loss: 0.7508 - accuracy: 0.5000
Epoch 8/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7504 - accuracy: 0.5000
Epoch 9/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7500 - accuracy: 0.5000
Epoch 10/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7495 - accuracy: 0.5000
Epoch 11/500
1/1 [===========

1/1 [==============================] - 0s 2ms/step - loss: 0.7215 - accuracy: 0.5000
Epoch 84/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7211 - accuracy: 0.5000
Epoch 85/500
1/1 [==============================] - 0s 1ms/step - loss: 0.7208 - accuracy: 0.5000
Epoch 86/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7205 - accuracy: 0.5000
Epoch 87/500
1/1 [==============================] - 0s 1ms/step - loss: 0.7201 - accuracy: 0.5000
Epoch 88/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7198 - accuracy: 0.5000
Epoch 89/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7194 - accuracy: 0.5000
Epoch 90/500
1/1 [==============================] - 0s 1ms/step - loss: 0.7191 - accuracy: 0.5000
Epoch 91/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7188 - accuracy: 0.5000
Epoch 92/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7184 - accuracy: 0.5000
Epoch 93/500
1/1 [===============

1/1 [==============================] - 0s 2ms/step - loss: 0.6972 - accuracy: 0.5000
Epoch 165/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6969 - accuracy: 0.5000
Epoch 166/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6967 - accuracy: 0.5000
Epoch 167/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6964 - accuracy: 0.5000
Epoch 168/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6962 - accuracy: 0.5000
Epoch 169/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6959 - accuracy: 0.5000
Epoch 170/500
1/1 [==============================] - 0s 937us/step - loss: 0.6956 - accuracy: 0.5000
Epoch 171/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6954 - accuracy: 0.5000
Epoch 172/500
1/1 [==============================] - 0s 1ms/step - loss: 0.6951 - accuracy: 0.5000
Epoch 173/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6949 - accuracy: 0.5556
Epoch 174/500
1/1 [===

1/1 [==============================] - 0s 2ms/step - loss: 0.6791 - accuracy: 0.5556
Epoch 247/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6789 - accuracy: 0.5556
Epoch 248/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6788 - accuracy: 0.5556
Epoch 249/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6786 - accuracy: 0.5556
Epoch 250/500
1/1 [==============================] - 0s 10ms/step - loss: 0.6784 - accuracy: 0.5556
Epoch 251/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6782 - accuracy: 0.5556
Epoch 252/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6780 - accuracy: 0.5556
Epoch 253/500
1/1 [==============================] - 0s 1ms/step - loss: 0.6779 - accuracy: 0.5556
Epoch 254/500
1/1 [==============================] - 0s 1ms/step - loss: 0.6777 - accuracy: 0.5556
Epoch 255/500
1/1 [==============================] - 0s 1ms/step - loss: 0.6775 - accuracy: 0.5556
Epoch 256/500
1/1 [====

1/1 [==============================] - 0s 3ms/step - loss: 0.6665 - accuracy: 0.5556
Epoch 329/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6664 - accuracy: 0.5556
Epoch 330/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6662 - accuracy: 0.5556
Epoch 331/500
1/1 [==============================] - ETA: 0s - loss: 0.6661 - accuracy: 0.55 - 0s 3ms/step - loss: 0.6661 - accuracy: 0.5556
Epoch 332/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6660 - accuracy: 0.5556
Epoch 333/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6658 - accuracy: 0.5556
Epoch 334/500
1/1 [==============================] - 0s 1ms/step - loss: 0.6657 - accuracy: 0.5556
Epoch 335/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6656 - accuracy: 0.5556
Epoch 336/500
1/1 [==============================] - 0s 1ms/step - loss: 0.6655 - accuracy: 0.5556
Epoch 337/500
1/1 [==============================] - 0s 1ms/step - loss: 0.6654 -

1/1 [==============================] - 0s 1ms/step - loss: 0.6578 - accuracy: 0.5556
Epoch 411/500
1/1 [==============================] - 0s 1ms/step - loss: 0.6577 - accuracy: 0.5556
Epoch 412/500
1/1 [==============================] - 0s 1ms/step - loss: 0.6576 - accuracy: 0.5556
Epoch 413/500
1/1 [==============================] - 0s 822us/step - loss: 0.6575 - accuracy: 0.5556
Epoch 414/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6575 - accuracy: 0.5556
Epoch 415/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6574 - accuracy: 0.5556
Epoch 416/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6573 - accuracy: 0.5556
Epoch 417/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6572 - accuracy: 0.5556
Epoch 418/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6571 - accuracy: 0.5556
Epoch 419/500
1/1 [==============================] - 0s 994us/step - loss: 0.6570 - accuracy: 0.5556
Epoch 420/500
1/1 [=

1/1 [==============================] - 0s 7ms/step - loss: 0.6518 - accuracy: 0.5556
Epoch 493/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6517 - accuracy: 0.5556
Epoch 494/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6516 - accuracy: 0.5556
Epoch 495/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6516 - accuracy: 0.5556
Epoch 496/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6515 - accuracy: 0.5556
Epoch 497/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6515 - accuracy: 0.5556
Epoch 498/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6514 - accuracy: 0.5556
Epoch 499/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6513 - accuracy: 0.5556
Epoch 500/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6513 - accuracy: 0.5556


In [7]:
model.evaluate(X_test_scaled,y_test)

1/1 [==============================] - 0s 1ms/step - loss: 0.5763 - accuracy: 0.8000


[0.5763158798217773, 0.800000011920929]

In [8]:
coef, intercept = model.get_weights()

In [9]:
# weights
coef

array([[0.76494205],
       [0.6370974 ]], dtype=float32)

In [10]:
#bias
intercept

array([-0.39183712], dtype=float32)

In [11]:
model.predict(X_test_scaled)

array([[0.67081535],
       [0.65888494],
       [0.6725023 ],
       [0.45191106],
       [0.60193825],
       [0.45380643],
       [0.6657281 ],
       [0.63442254],
       [0.61288226],
       [0.4576011 ]], dtype=float32)

# Implementation from Scratch

In [6]:
# to calculate the log loss(Binary cross entropy)
def log_loss(y_real, y_predicted):
    epsilon = 1e-15
    # convert the 0 to epsilon
    y_predicted = [max(i,epsilon) for i in y_predicted]
    # convert 1 to 1-epsilon
    y_predicted = np.array([min(i,1-epsilon) for i in y_predicted])
    logLoss = -np.mean(y_real*np.log(y_predicted)+(1-y_real)*np.log(1-y_predicted))
    return logLoss

In [7]:
# apply the sigmoid fucntion on a whole array
def sigmoid_numpy(x):
    return 1/(1+np.exp(-x))

In [21]:
class myNN:
    def __init__(self):
        self.w1 = 1
        self.w2 = 1
        self.bias = 0
    
    def fit(self, X, y, epochs, loss_threshold):
        self.w1, self.w2, self.bias = self.gradient_descent(X['age'], X['affordibility'], y, epochs, loss_threshold)
    
    def predict(self, X_test):
        weighted_sum = self.w1*X_test['age'] + self.w2*X_test['affordibility'] + self.bias
        return sigmoid_numpy(weighted_sum)
    
    def gradient_descent(self, age, affordibility, y_true, epochs, loss_threshold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5 # learning rate
        n = len(age)

        for i in range(epochs):
            weighted_sum = w1*age + w2*affordibility + bias
            y_predicted = sigmoid_numpy(weighted_sum)
            loss = log_loss(y_true,y_predicted)

            #fiding the derivatives
            w1_d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
            w2_d = (1/n)*np.dot(np.transpose(affordibility),(y_predicted-y_true))
            bias_d = np.mean(y_predicted-y_true)

            # updating the weights and bias
            w1 = w1 - rate*w1_d
            w2 = w2 - rate*w2_d
            bias = bias - rate*bias_d
            
            if i%25 == 0:
                print(f'Epoch: {i}, w1: {w1}, w2: {w2}, bias: {bias}, loss: {loss}')

            if(loss<=loss_threshold):
                print(f'Epoch: {i}, w1: {w1}, w2: {w2}, bias: {bias}, loss: {loss}')
                break
        print(f'Epoch: {i}, w1: {w1}, w2: {w2}, bias: {bias}, loss: {loss}')
        return w1,w2,bias


In [23]:
customModel = myNN()
customModel.fit(X_train_scaled, y_train, epochs=500, loss_threshold = 0.515)

Epoch: 0, w1: 0.9735870554090863, w2: 0.9276373851660089, bias: -0.11621401159689329, loss: 0.7533655791117272
Epoch: 25, w1: 1.1626593722282215, w2: 0.6743131347272098, bias: -0.8354207861038951, loss: 0.6229659931083777
Epoch: 50, w1: 1.5302272080895147, w2: 0.7467614156091524, bias: -1.0412437858276409, loss: 0.6082731052450916
Epoch: 75, w1: 1.8835637469266067, w2: 0.7979939232650832, bias: -1.2219301317556364, loss: 0.5954089542992953
Epoch: 100, w1: 2.2207626631778417, w2: 0.8354187456545137, bias: -1.3855501801817134, loss: 0.5840147278521037
Epoch: 125, w1: 2.541543394768044, w2: 0.8643650451290783, bias: -1.5361180415319018, loss: 0.5738645001606684
Epoch: 150, w1: 2.846163007780166, w2: 0.8880773551425616, bias: -1.67625053116322, loss: 0.5647925375477527
Epoch: 175, w1: 3.135181465527246, w2: 0.9085300968765314, bias: -1.807704707270465, loss: 0.5566655711125256
Epoch: 200, w1: 3.4093186848209664, w2: 0.9269229884226572, bias: -1.9317005092755386, loss: 0.549371253786572
Epo

In [24]:
customModel.predict(X_test_scaled)

9     0.806168
25    0.745901
8     0.813828
21    0.205786
0     0.373797
12    0.214041
17    0.781764
22    0.593875
11    0.445886
13    0.231264
dtype: float64

In [12]:
model.predict(X_test_scaled)

array([[0.67081535],
       [0.65888494],
       [0.6725023 ],
       [0.45191106],
       [0.60193825],
       [0.45380643],
       [0.6657281 ],
       [0.63442254],
       [0.61288226],
       [0.4576011 ]], dtype=float32)